"""Network hardening.

Three separable pieces, in increasing order of what they require:

* system settings that stop the device using Chinese NTP and captive-portal
  endpoints -- plain adb, no root;
* a systemless hosts Magisk module built from the Onyx blocklist -- needs root,
  but writes nothing to a partition, so it is trivially reversible;
* guidance for a real firewall, because a hosts file cannot block the cloud
  index bootstrap that Onyx reaches by hardcoded IP.

There is also a scaffold for the ``services.jar`` fix that this device needs to
make the Magisk app usable. That one cannot be fully automated here and says so
plainly rather than pretending.
"""

from __future__ import annotations

import zipfile
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from boox.console import banner, info, ok, step, warn
from boox.errors import BooxError
from boox.transport.adb import Adb

# Reached over plain HTTP by hardcoded IP, carrying the device MAC. A hosts file
# cannot touch an IP literal, so this needs a firewall rule.
CLOUD_INDEX_IP = "119.23.143.188"

# NTP and connectivity checks. The stock values point at Chinese infrastructure,
# so the device contacts it on every boot and every network change.
SETTINGS = {
    "ntp_server": "pool.ntp.org",
    "ntp_server_2": "time.cloudflare.com",
    "captive_portal_http_url": "http://connectivitycheck.gstatic.com/generate_204",
    "captive_portal_https_url": "https://connectivitycheck.gstatic.com/generate_204",
    "captive_portal_fallback_url": "http://connectivitycheck.gstatic.com/generate_204",
    "captive_portal_mode": "1",
}


def blocklist_domains() -> list[str]:
    text = resources.files("boox.data.blocklist").joinpath("onyx-hosts.txt").read_text(
        encoding="utf-8"
    )
    return [
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


@dataclass
class SettingsResult:
    applied: dict[str, str]
    failed: dict[str, str]


def apply_settings(adb: Adb, *, dry_run: bool = False) -> SettingsResult:
    """Point NTP and connectivity checks away from Chinese infrastructure."""
    applied: dict[str, str] = {}
    failed: dict[str, str] = {}
    step("redirecting NTP and captive-portal checks")
    for key, value in SETTINGS.items():
        if dry_run:
            info(f"dry run: settings put global {key} {value}")
            applied[key] = value
            continue
        result = adb.shell(f"settings put global {key} {value}", timeout=30)
        if result.ok:
            applied[key] = value
        else:
            failed[key] = result.tail(2)
            warn(f"{key}: {result.tail(1)}")
    ok(f"{len(applied)} settings applied" + (f", {len(failed)} failed" if failed else ""))
    return SettingsResult(applied, failed)


def build_hosts_module(dest: Path, *, extra_domains: list[str] | None = None) -> Path:
    """Build a Magisk module that overlays /system/etc/hosts.

    Systemless: Magisk mounts it over the real file, so uninstalling the module
    is a complete undo and no partition is written.
    """
    domains = blocklist_domains() + list(extra_domains or [])
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated by boox-boot-tool.",
        "# Remove the module in Magisk to undo all of this.",
        "127.0.0.1   localhost",
        "::1         ip6-localhost",
        "",
    ]
    for domain in domains:
        lines.append(f"0.0.0.0   {domain}")
    hosts = "\n".join(lines) + "\n"

    prop = "\n".join([
        "id=boox_onyx_blocklist",
        "name=Boox Onyx Blocklist",
        "version=v1",
        "versionCode=1",
        "author=boox-boot-tool",
        f"description=Null-routes {len(domains)} Onyx telemetry and cloud hosts. "
        "Boox account sync, the app store and OTA checks stop working while this is enabled.",
    ]) + "\n"

    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("module.prop", prop)
        archive.writestr("system/etc/hosts", hosts)
    ok(f"hosts module written: {dest} ({len(domains)} domains)")
    return dest


def install_module(adb: Adb, module_zip: Path, *, dry_run: bool = False) -> None:
    """Install a Magisk module over adb. Requires root."""
    remote = f"/data/local/tmp/{Path(module_zip).name}"
    if dry_run:
        info(f"dry run: would push {module_zip} and run 'magisk --install-module {remote}'")
        return
    if not adb.is_rooted():
        raise BooxError(
            "the device does not appear to be rooted",
            remedy="Run 'boox root prepare' and 'boox root apply' first.",
        )
    adb.push(Path(module_zip), remote)
    result = adb.shell(f"su -c 'magisk --install-module {remote}'", timeout=180)
    if not result.ok or "error" in result.output.lower():
        raise BooxError(
            f"installing the module failed:\n{result.tail()}",
            remedy="Install the zip by hand from the Magisk app instead.",
        )
    ok("module installed; reboot for it to take effect")


def firewall_guidance() -> str:
    return (
        f"A hosts file cannot block {CLOUD_INDEX_IP}, which Onyx reaches directly by IP\n"
        f"over plain HTTP and which receives the device's MAC address. To stop that you\n"
        f"need a real firewall:\n\n"
        f"  AFWall+ (root, iptables)  - whitelist mode, allow only the apps you use\n"
        f"  NetGuard  (no root, VPN)  - simpler, but cannot see through a VPN you also want\n\n"
        f"Either way, add an explicit deny for {CLOUD_INDEX_IP}.\n"
        f"Blocking at your router or Pi-hole covers the device on your own network only."
    )


def ams_fix_scaffold(adb: Adb, workdir: Path) -> Path:
    """Pull this device's services.jar and lay out a module around it.

    The actual fix is a smali edit to the check Onyx added to
    ActivityManagerService, and it is specific to each firmware build -- the
    prebuilt community module ships a jar from a different model and will not
    work here. So this stops at the point where a real decision is needed
    instead of producing something that looks finished and is not.
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    local = workdir / "services.jar"

    step("pulling /system/framework/services.jar from the device")
    adb.pull("/system/framework/services.jar", local)
    if not local.is_file():
        raise BooxError(
            "could not pull services.jar",
            remedy="The device must be booted into Android with adb working.",
        )
    ok(f"{local} ({local.stat().st_size} bytes)")

    banner(
        "services.jar fix: manual step required",
        f"Magisk's app hangs on its splash screen on this firmware because of a check\n"
        f"Onyx added to ActivityManagerService. Root works; only the app is affected.\n\n"
        f"The prebuilt boox-ams-fix module ships a services.jar built for a different\n"
        f"model. Installing it here leaves Magisk hung in exactly the same way, so use\n"
        f"the jar just pulled from this device:\n\n"
        f"  1. baksmali d {local} -o {workdir / 'smali'}\n"
        f"  2. patch the AMS check (see github.com/dynamicfire/boox-ams-fix for which)\n"
        f"  3. smali a {workdir / 'smali'} -o {workdir / 'classes.dex'}\n"
        f"  4. repackage into a copy of the boox-ams-fix module zip\n"
        f"  5. boox harden --install-module <your-module.zip>\n\n"
        f"This has to be redone whenever Onyx ships a new services.jar.",
        style="warn",
    )
    return local


def summary(domains: int) -> str:
    return (
        f"Hardening covers three layers:\n"
        f"  settings   NTP and captive-portal checks moved off Chinese endpoints\n"
        f"  hosts      {domains} Onyx domains null-routed via a systemless Magisk module\n"
        f"  firewall   still yours to configure -- see the note about {CLOUD_INDEX_IP}"
    )
